CREATE TABLE COUNTRIES
  COUNTRY_ID NOT NULL CHAR(2)
  COUNTRY_NAME VARCHAR(40)
  REGION_ID NUMBER;


CREATE TABLE DEPARTMENTS
  DEPARTMENT_ID NUMBER(4) NOT NULL
  DEPARTMENT_NAME VARCHAR2(30) NOT NULL
  MANAGER_ID NUMBER(6)
  LOCATION_ID NUMBER(4);


CREATE TABLE EMPLOYEES
  EMPLOYEE_ID NOT NULL NUMBER(6)
  FIRST_NAME VARCHAR2(20)
  LAST_NAME NOT NULL VARCHAR2(25)
  EMAIL NOT NULL VARCHAR2(20)
  PHONE_NUMBER VARCHAR2(20)
  HIRE_DATE NOT NULL DATE
  JOB_ID NOT NULL VARCHAR2(10)
  SALARY NUMBER(8,2)
  COMMISSION_PCT NUMBER(2,2)
  MANAGER_ID NUMBER(6)
  DEPARTMENT_ID NUMBER(4);


CREATE TABLE JOBS
  JOB_ID NOT NULL VARCHAR2(10)
  JOB_TITLE NOT NULL VARCHAR2(35)
  MIN_SALARY NUMBER(6)
  MAX_SALARY NUMBER(6);


CREATE TABLE JOB_HISTORY
  EMPLOYEE_ID NOT NULL NUMBER(6)
  START_DATE NOT NULL DATE
  END_DATE NOT NULL DATE
  JOB_ID NOT NULL VARCHAR2(10)
  DEPARTMENT_ID NUMBER(4);


CREATE TABLE LOCATIONS
  LOCATION_ID NOT NULL NUMBER(4)
  STREET_ADDRESS VARCHAR2(40)
  POSTAL_CODE VARCHAR2(12)
  CITY NOT NULL VARCHAR2(30)
  STATE_PROVINCE VARCHAR2(25)
  COUNTRY_ID CHAR(2);


CREATE TABLE REGIONS
  REGION_ID NOT NULL NUMBER
  REGION_NAME VARCHAR2(25)

VARCHAR TEXT NUMBER CHAR DATE